export default {
  APPEND_JOKES: 'APPEND_JOKES',
  SET_CATEGORIES: '`SET_CATEGORIES',
  SET_ACTIVE_CATEGORY: 'SET_ACTIVE_CATEGORY',
  SET_JOKES_FETCHING: 'SET_JOKES_FETCHING',
  SET_JOKES_RECEIVED: 'SET_JOKES_RECEIVED'
};
